### ISSUE TITLE
How to copy entire cart to another?

### ISSUE THREAD

**Issue by orionlu0916** [anam-hossain/phpcart#1]
Hi! there, I wondering if it is possible to copy entire cart items to another one?
For example, if before a guest login, I'll  have a default cart for the guest.
but once the guest login, I'll use his user name to create a new cart.
so, I want to do some thing like this:
$guestCart = new Cart('guest');
$userCart  = new Cart(Session::get('username'));
// Pass all "guestCart" Items into "$userCart"
$guestCart->flash();

How can I do this kind of things?
Thank you so much

**Comment by anam-hossain** [comment]
@orionlu0916 I just added this feature to the `PHPCart`. Just run `composer update`.

``` php
$userCart->copy($guestCart);
```

### Usage

``` php
$guestCart = new Cart('guest');

$guestCart->add([
  'id'       => 1001,
 'name'     => 'Skinny Jeans',
 'quantity' => 1,
 'price'    => 90
]);

$userCart = new Cart(Session::get('username'));

$userCart->copy($guestCart);

$guestCart->flash();
var_dump($userCart->items());
```

**Comment by orionlu0916** [comment]
@anam-hossain Thank you for your reply, Your change it perfect, and I saw you also change the session starting stuff, that also helps for the implantation of my work! This is really awesome, Thanks a lot!
