### ISSUE TITLE
Getting Error : Some required fields missing: id,name,price,quantity

### ISSUE THREAD

**Issue by hernandoferry** [anam-hossain/phpcart#12]
Hai @anam-hossain, i try to learn your phpcart but i get the error Some required fields missing: id,name,price,quantity. and my question is how to convert id,name,price and quantity to my json like this 
{
"status": true,
"message": null,
"data": {
"count": "1",
"data": [
{
"category_parent_id": 0,
"product_unit_price": 300000,
"city_id": "187",
"product_picture_1": "4.jpg",
"product_color": "White",
"brand_id": 47,
"product_discount": 0,
"product_shipper": "NCS HealthCare of KY, Inc dba Vangard Labs",
"product_stock": 161,
"product_price": 300000,
"product_name": "Izora tunik",
"product_picture_4": "7.jpg",
"product_picture_5": "8.jpg",
"product_variant": "White, Pink, Brown",
"product_picture_3": "6.jpg",
"product_label": "Movies",
"product_min_order": 1,
"merchant_id": "8",
"pp_id": "72",
"product_weight": 565,
"product_popular": "true",
"product_id": "2",
"created_at": "2018-03-14 11:09:11.742656",
"product_size": "One Size",
"attribute_id": 1,
"product_condition": 1,
"product_picture_2": "5.jpg",
"category_id": 2
}

]
}
}

**Comment by anam-hossain** [comment]
Closing as it is an implementation issue.
