### ISSUE TITLE
How can we increase session time in this cart?

### ISSUE THREAD

**Issue by Khalid12345678** [anam-hossain/phpcart#15]
I have integrated your cart package in my domain https://www.vanagain.com/ . While i logged in on my website and add the products in cart, after 20-30 min the cart items remove automatically but all other eg. login session working fine which i have set for 2 days in my laravel application.

**Comment by Khalid12345678** [comment]
How can i increase session time for the cart items?

**Comment by RedwevertonHub** [comment]
Im having this problem too, some users are losing thir data stone in 'cart' after some minutes... I really wanna now how to increase this.

**Comment by tarun-deaninfotech** [comment]
I am facing this issue too since many months. Can you please rectify this issue in package asap?

Really appreciate your help

**Comment by anam-hossain** [comment]
@Khalid12345678 @RedwevertonHub @tarun-deaninfotech a new version (v1.1.0) has been released to allow a developer to set session time. In addition to session time, you can set the following settings:

https://github.com/symfony/http-foundation/blob/master/Session/Storage/NativeSessionStorage.php#L362-L372

```php
// In seconds. Default to 7 days
$options = ['gc_maxlifetime' => 604800];

$cart = new Cart('test', null, $options);
```

If you don't like to set the session time, the implementation is the same as before.

```php
$cart = new Cart();
```

**Comment by tarun-deaninfotech** [comment]
Hey @Anam-Hossain,

Thanks for the update. I will try using the update as you mentioned.

**Comment by Khalid12345678** [comment]
Hey @anam-hossain 
Thanks for the update.

**Comment by tarun-deaninfotech** [comment]
Hey @anam-hossain,

if you check in config/Session.php,
There is a key 'lifetime' => env('SESSION_LIFETIME', 120),

Can you please replicate this key in your code so that it will be global key for the entire package.

Thanks!

**Comment by tarun-deaninfotech** [comment]
> @Khalid12345678 @RedwevertonHub @tarun-deaninfotech a new version (v1.1.0) has been released to allow a developer to set session time. In addition to session time, you can set the following settings:
> 
> https://github.com/symfony/http-foundation/blob/master/Session/Storage/NativeSessionStorage.php#L362-L372
> 
> ```
> // In seconds. Default to 7 days
> $options = ['gc_maxlifetime' => 604800];
> 
> $cart = new Cart('test', null, $options);
> ```
> 
> If you don't like to set the session time, the implementation is the same as before.
> 
> ```
> $cart = new Cart();
> ```

Just tried as you explained but not working for me. Can you please try once in incognito window?

**Comment by RedwevertonHub** [comment]
@anam-hossain I will try it ASAP and feedback, in advance thanks for the update.

**Comment by anam-hossain** [comment]
@RedwevertonHub @Khalid12345678 @tarun-deaninfotech If you guys using Laravel, I recommend to use https://github.com/anam-hossain/lara-phpcart. This package only developed for Laravel users and can utilize Laravel session. Almost no need to change any code.

**Comment by RedwevertonHub** [comment]
@anam-hossain Wait, im using Laravel 5.5, i need use the following code too?
`// In seconds. Default to 7 days
$options = ['gc_maxlifetime' => 604800];

$cart = new Cart('test', null, $options);`

Im little confused right now...I need change in laravel or need use this update, or i need to update my phpcart?

**Comment by anam-hossain** [comment]
@RedwevertonHub PHPcart is framework agnostic. It means, it is a pure PHP package. The package can be used in Symfony, Laravel or even with pure PHP code. The PHPcart session is handled using Symfony Http foundation NOT Laravel. 

As you are using Laravel for your project. It will be easy for you to migrate to <a href="https://github.com/anam-hossain/lara-phpcart">lara-phpcart</a> package. You don't have to change any code at all. The package uses the Laravel session. It means Laravel control the session NOT the package. So, to update session settings, all you need to do is update the Laravel's session config.

**Comment by RedwevertonHub** [comment]
@anam-hossain ooh ok, i understand now, thank you, i will change anam/phpcart to lara-phpcart in my project, i already changed lifetime session in laravel, so i think that will work fine.

**Comment by anam-hossain** [comment]
Closing as PHPcart v1.1.0 accepts session settings.
