### ISSUE TITLE
How do I render the cart items?

### ISSUE THREAD

**Issue by sladeos** [anam-hossain/phpcart#2]
I've managed to create a cart, add an item to the cart and send it to my view. But how do I go about looping through the returned object from $cart = getItems();
This is what's printed from dd($cart); after getItems(); 
http://imgur.com/KEq3KRb

I'm using the Laravel framework and I've tried something like this 
Where $cart is the return from getItems()
           @foreach($cart as $item)
            {{$item->name}}
            @endforeach

But nothing is printed. I'm new to php and having a hard time with this.

Thanks in advance!

**Comment by grupp3pvt15** [comment]
Don't worry, sorry :D
