### ISSUE TITLE
Sorting cart?

### ISSUE THREAD

**Issue by sladeos** [anam-hossain/phpcart#6]
Is there a way to sort the cart by id or a certain attribute?

**Comment by anam-hossain** [comment]
PHPCart utilise the Laravel's Collection. So you can use any one of the following methods:
http://laravel.com/docs/5.1/collections#available-methods

Example:

``` php
$items = $cart->getItems();
$sorted = $items->sort();
```

**Comment by sladeos** [comment]
Oh of course! Thank you!
