### ISSUE TITLE
Composer Conflict With Laravel 5.3

### ISSUE THREAD

**Issue by perfectpitchconcepts** [anam-hossain/phpcart#9]
I've been enjoying your plugin on one of my projects for well over a year now. But I'm running into some issues trying to upgrade my Laravel version to 5.3. Getting a notice about version conflicts with "symfony/http-foundation" with phpcart and the Laravel packages, since that now seems to be using v3.1. 

Was just curious if this might be something that could be updated in your package easily? Or if there is a workaround on my end (beyond trying to create my own branch or switching to another cart)?

If you're not supporting this anymore, no worries. Just thought it was worth checking. Regardless, thanks for the great work on this!

**Comment by anam-hossain** [comment]
Just pushed a new version. Composer update will fix the issue.

Let me know its working or not.

Thanks for the error reporting.

**Comment by perfectpitchconcepts** [comment]
Thanks, that did the trick!
